### ISSUE TITLE
ไม่ต้องเช็ก Perm ว่าปิดหูฟังตัวเองได้ไหมในห้อง Stage

### ISSUE THREAD

**Issue by manybaht** [manybaht/manybaht_v2#19]

**Comment by manybaht** [comment]
- เพิ่มเช็กว่าบอทสามารถขึ้นพูดได้ไหม

**Comment by illyaz** [comment]
บอทสามารถปิดหูฟังในห้อง Stage ได้โดยที่ไม่ต้องมี Perm
บอทสามารถขึ้นพูดได้เมื่อ mod เชิญ

สรุปไม่ต้องแก้อะไรทั้งนั้น
