### ISSUE TITLE
ให้ทุก Cluster เก็บ และ ส่งสถิติไปที่ส่วนกลาง

### ISSUE THREAD

**Issue by manybaht** [manybaht/manybaht_v2#3]
เก็บข้อมูลดังต่อไปนี้
จำนวนการใช้คำสั่ง แยกแต่ละคำสั่ง
10 อันดับลิงก์ที่เล่นมากที่สุด

ส่งไปเป็น JSON ที่ส่วนกลาง

**Comment by illyaz** [comment]
ส่วนกลางส่งต่อเข้าฐานข้อมูลแบบ batch
